[package]
name = "codeforces-extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
reqwest = { version = "0.12.9", features = ["blocking"] }
tl = "0.7.8"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
regex = "1.3.9"
